"""Agregar tabla VINs

Revision ID: db6ad0139c95
Revises: 568da1de435f
Create Date: 2025-01-21 19:09:18.765620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db6ad0139c95'
down_revision = '568da1de435f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VIN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('vin_completo', sa.String(length=17), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.drop_table('vins')
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('license_expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('secuencial', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_year', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('username', name='usuarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vins',
    sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c4', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c5', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c6', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c7', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c8', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c10', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('c11', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('secuencial', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('vin_completo', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.username'], name='vins_owner_id_fkey')
    )
    op.drop_table('subscriptions')
    op.drop_table('VIN')
    # ### end Alembic commands ###
